data<-read.csv(file.choose(),header=TRUE)
head(data)
d1<-subset(data,Date=="1/2/2007")
d2<-subset(data,Date=="2/2/2007")
nd<-rbind(d1,d2)
dim(nd)
plot(nd$Global_active_power,ylab="Global Active Power(kilowatts)",type="l")
dev.copy(png,file="plot2.png")
dev.off()
