data<-read.csv(file.choose(),header=TRUE)
head(data)
d1<-subset(data,Date=="1/2/2007")
d2<-subset(data,Date=="2/2/2007")
nd<-rbind(d1,d2)
dim(nd)
hist(nd$Global_active_power,col="red",xlim=c(0,6),main="Global Active Power",xlab="Global Active Power(kilowatts)",ylab="frequency")
dev.copy(png,file="plot1.png")
dev.off()
