data<-read.csv(file.choose(),header=TRUE)
head(data)
d1<-subset(data,Date=="1/2/2007")
d2<-subset(data,Date=="2/2/2007")
nd<-rbind(d1,d2)
dim(nd)
plot(nd$Sub_metering_1,ylab="Energy submerging",type="l")
lines(nd$Sub_metering_2,col="red")
lines(nd$Sub_metering_3,col="blue")
legend("topright",legend=c("sub_mergin_1","sub_mergin_2","sub_mergin_3"),cex=0.6,col=c("black","red","blue"),lty=1)
dev.copy(png,file="plot3.png")
dev.off()
